# Generated by Django 5.0.3 on 2025-06-10 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc_processing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
