# Generated by Django 5.0.3 on 2025-07-15 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc_processing', '0002_document_processed_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedDocumentProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Processed Document',
                'verbose_name_plural': 'Processed Documents',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('doc_processing.document',),
        ),
        migrations.CreateModel(
            name='UnprocessedDocumentProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Unprocessed Document',
                'verbose_name_plural': 'Unprocessed Documents',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('doc_processing.document',),
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
