# Generated by Django 5.0.3 on 2025-07-23 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_conversation_last_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='feedback',
            field=models.TextField(default=''),
        ),
    ]
