# Generated by Django 5.0.3 on 2025-07-30 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_message_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='feedback',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
